export enum AppColors {
  tintColor = '#040037',
  tabIconDefault = '#CCC',
  tabIconSelected = '#040037',
  tabBar = '#FEFEFE',
  errorBackground = 'red',
  errorText = '#FFF',
  warningBackground = '#EAEB5E',
  warningText = '#666804',
  noticeBackground = '#040037',
  noticeText = '#FFF',
  tabBarBackground = '#FFF',
  inAppBrowserLayout = '#040037',
  inAppBrowserIcon = '#FFF',
  newWordingText = '#4CAF50',
  newWordingBackground = '#4CAF5026',
}
